---
# tasks file for squidguard

- name: Install SquidGuard
  apt: pkg={{ squidguard_package }} state=installed update_cache=true
  register: squidguardinstalled

- name: Copy SquidGuard Config
  when: squidguardinstalled|success
  copy: src={{ squidguard_source_config }} dest={{ squidguard_path }} owner=proxy group=proxy force=yes
  register: squidguardconfigured

- name: Add url_rewrite_program to Squid Config
  when: squidguardconfigured|success
  lineinfile: 
    dest: "{{ squid3_conf }}" 
    line: "{{ item }}"
    insertbefore: BOF
    state: present
  with_items:
    - "url_rewrite_program /usr/bin/squidGuard -c {{ squidguard_conf }}" 
    - "url_rewrite_children 20"
  notify: Restart Squid3
  
- name: Copy Blacklists
  when: squidguardconfigured|success
  unarchive: src={{ squidguard_source_blacklists }} dest={{ squidguard_dbhome }} owner=root group=root copy=yes
  
- name: Create DB files
  when: squidguardconfigured|success
  command: /usr/bin/squidGuard -C all
  
- name: Change files ownership and permissions
  when: squidguardconfigured|success
  file:
    path: "{{ squidguard_dbhome }}"
    owner: proxy
    group: proxy
    mode: u=rwX,g=rX,o=rX
    recurse: yes