---
# tasks file for squid3

- name: Install Squid3
  apt: pkg={{  squid3_package }} state=installed update_cache=true
  
- name: Start Squid3
  service: name={{ squid3_daemon }} state=started enabled=yes

- name: Backup Config
  command: creates={{ squid3_conf }}.bak cp {{ squid3_conf }} {{ squid3_conf }}.bak

- name: Copy Config
  copy: src={{ squid3_source_config }} dest={{ squid3_path }} owner=root group=root force=yes
  notify: Restart Squid3
  